### ISSUE TITLE
Change to find -perm for newer systems

### ISSUE THREAD

**Issue by nigaffney** [SD2E/sd2e-cli#1]
The sd2e command is failing on Centos 7.1 with the error

find: warning: you are using `-perm +MODE'.  The interpretation of `-perm +omode' changed in findutils-4.5.11.  The syntax `-perm +omode' was removed in findutils-4.5.12, in favour of `-perm /omode'.

Changing the + to a / worked on Wrangler and I think will work on some other systems but...I don't know how backportable that is.

**Comment by johnfonner** [comment]
I'm going to close this issue.  After the fix last November, we haven't seen this issue crop up again.  I'm worried there are still edge cases where some OSes will still get the wrong formatting of the find command, but it's apparently rare enough that we haven't encountered it yet.
