### ISSUE TITLE
Downloading without permissions creates fake file

### ISSUE THREAD

**Issue by jakebeal** [SD2E/sd2e-cli#4]
If your permissions aren't set up right and you try to download a file, you appear to succeed.
What you have downloaded, however, is a text file containing:

`{"fault":{"code":900902,"message":"Missing Credentials","description":"Required OAuth credentials not provided. Make sure your API invocation call has a header: \"Authorization: Bearer ACCESS_TOKEN\""}}`

**Comment by alejandrox1** [comment]
Taking this one

**Comment by alejandrox1** [comment]
The fix has to be done on the [agave cli](https://github.com/TACC-Cloud/agave-cli/pull/17).
