### ISSUE TITLE
`sd2e info --upgrade` does not appear to work

### ISSUE THREAD

**Issue by tcmitchell** [SD2E/sd2e-cli#6]
I downloaded the [tarball](https://raw.githubusercontent.com/sd2e/sd2e-cli/master/sd2e-cloud-cli.tgz) this morning to update from 1.0.1 to 1.0.6, following the manual install section in https://sd2e.github.io/api-user-guide/docs/install_cli.html.

Once I unpacked it and made sure it was in my path, I ran `sd2e info` and it said:

```
$ sd2e info

DARPA SD2E version: 1.0.6
TACC Cloud API tenant: sd2e.org
TACC Cloud API versions:
	Science APIs: 2.2.5
	Reactors API: dev
	TACC Accounting API: v1

An update is available (1.0.6 installed - 1.0.7 available)
Re-run /Users/tmitchel/Projects/sd2/sd2e-cloud-cli/bin/subcommands/info with --upgrade to install it.
```

So i tried that:

```
$ sd2e info --upgrade
Done.
```

And then ran info again to find that it still reports version 1.0.6 and still offers to upgrade to 1.0.7:

```
$ sd2e info

DARPA SD2E version: 1.0.6
TACC Cloud API tenant: sd2e.org
TACC Cloud API versions:
	Science APIs: 2.2.5
	Reactors API: dev
	TACC Accounting API: v1

An update is available (1.0.6 installed - 1.0.7 available)
Re-run /Users/tmitchel/Projects/sd2/sd2e-cloud-cli/bin/subcommands/info with --upgrade to install it.
```

Running `sd2e info --upgrade` again (and again) results in the same output.

If it matters, I'm on a Mac running macOS Sierra 10.12.6.

**Comment by mwvaughn** [comment]
Thanks for bringing this to our attention. We think it's a cacheing issue with Github file distribution. For now, you can get the latest version from https://github.com/SD2E/sd2e-cli/releases.

**Comment by tcmitchell** [comment]
Reading the code for subcommands/info, my take is that sd2e-cloud-cli.tgz did not get updated when the VERSION file got updated yesterday. The tgz file still shows as 22 days old, while the updated VERSION file shows 20 hours ago.

**Comment by tim-tx** [comment]
I think the problem is that https://github.com/SD2E/sd2e-cli/blob/master/sd2e-cloud-cli.tgz right now has a file `SDK-VERSION` with contents `1.0.6`, and `bin/subcommands/info` uses this as the version number. Put `1.0.7` in `SDK-VERSION` and the upgrade message goes away.
