### ISSUE TITLE
taccreg does not work on linux

### ISSUE THREAD

**Issue by zyndagj** [SD2E/sd2e-cli#9]
Docker needs to run with `sudo` on linux systems, and `sudo taccreg login` does NOT work. In all scripts where docker called, we need to:

- test to see if the host is running linux with `uname -s`
  - IF `Linux` then prefix docker with `sudo`
  - ELSE run as is

**Comment by alejandrox1** [comment]
@zyndagj what exactly is the problem when running `sudo taccreg login`?

**Comment by zyndagj** [comment]
### Without sudo

```
gzynda@js-168-216:~$ taccreg login
[NOTE] Log into Docker Registry:
Registry username []: gzynda
Registry password []: 
Registry organization (optional) []: 
Authenticating as gzynda...
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
Authentication failed
```
### With sudo
```
gzynda@js-168-216:~$ sudo taccreg login
sudo: taccreg: command not found
```
It seems that my `.bashrc` is not loaded with sudo because the following works.
```
gzynda@js-168-216:~$ sudo ~/sd2e-cloud-cli/bin/taccreg login
[NOTE] Log into Docker Registry:
Registry username []: gzynda
Registry password []: 
Registry organization (optional) []: 
Authenticating as gzynda...
Login Succeeded
```
However, requiring linux users to execute the full path of scripts does not seem ideal. I also don't know if other functionality is broken by this requirement.
